"use client";
import {useMemo,useState} from "react";import {useRouter} from "next/navigation";import type {Service} from "@/lib/types";import {usePersistentLocale} from "@/lib/locale-client";

type Slot={startAt:string;endAt:string;remaining:number;capacity:number;label:string};
const pad=(n:number)=>String(n).padStart(2,"0");const datePlus=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
async function jsonResponse(res:Response){const text=await res.text();if(!text)return{};try{return JSON.parse(text)}catch{throw new Error("invalid_response")}}
const copy={
fr:{eyebrow:"Rendez-vous",title:"Quand préférez-vous venir ?",lead:"Choisissez d'abord une date, puis une heure disponible.",date:"Date",preference:"Préférence",morning:"Matin",afternoon:"Après-midi",allDay:"Toute la journée",show:"Voir les créneaux disponibles",searching:"Recherche…",available:"Heures disponibles",none:"Aucun créneau disponible pour cette date.",places:(n:number)=>`${n} place${n>1?"s":""}`,summary:"Votre rendez-vous",confirm:"Confirmer ce rendez-vous",confirming:"Confirmation…",selected:"Sélectionné",prep:"À prévoir pour votre rendez-vous",id:"Pièce d'identité",rx:"Ordonnance ou demande médicale si disponible",note:"Les éventuelles consignes spécifiques à l'examen seront communiquées ou confirmées par le professionnel de santé.",searchError:"Impossible de charger les créneaux. Veuillez réessayer.",confirmError:"Une erreur est survenue lors de la confirmation du rendez-vous. Veuillez réessayer."},
ar:{eyebrow:"موعد",title:"وقتاش تحب تجي؟",lead:"اختار التاريخ أولاً، وبعدها اختار الوقت المتاح.",date:"التاريخ",preference:"الفترة",morning:"الصباح",afternoon:"بعد الظهر",allDay:"النهار الكل",show:"شوف المواعيد المتاحة",searching:"جاري البحث…",available:"الأوقات المتاحة",none:"ما فماش موعد متاح في التاريخ هذا.",places:(n:number)=>`${n} بلاصة`,summary:"موعدك",confirm:"أكد الموعد",confirming:"جاري التأكيد…",selected:"تم الاختيار",prep:"شنوة يلزمك للموعد",id:"بطاقة تعريف",rx:"وصفة أو طلب طبي إذا متوفر",note:"أي تعليمات خاصة بالفحص يثبتها أو يبعثها المهني الصحي.",searchError:"تعذر تحميل المواعيد. عاود حاول.",confirmError:"صار مشكل وقت تأكيد الموعد. عاود حاول."},
en:{eyebrow:"Appointment",title:"When would you like to come?",lead:"Choose a date first, then select an available time.",date:"Date",preference:"Preference",morning:"Morning",afternoon:"Afternoon",allDay:"All day",show:"See available times",searching:"Searching…",available:"Available times",none:"No available time for this date.",places:(n:number)=>`${n} place${n>1?"s":""}`,summary:"Your appointment",confirm:"Confirm this appointment",confirming:"Confirming…",selected:"Selected",prep:"Bring to your appointment",id:"Identity document",rx:"Prescription or medical request if available",note:"Any exam-specific instructions will be communicated or confirmed by the healthcare professional.",searchError:"Unable to load available times. Please try again.",confirmError:"An error occurred while confirming the appointment. Please try again."}}

export function BookingClient({service}:{service:Service}){const router=useRouter();const {locale}=usePersistentLocale();const c=copy[locale];const [period,setPeriod]=useState<"morning"|"afternoon"|"">("");const [selectedDate,setSelectedDate]=useState(datePlus(1));const [slots,setSlots]=useState<Slot[]>([]);const [selected,setSelected]=useState("");const [searched,setSearched]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const selectedSlot=useMemo(()=>slots.find(s=>s.startAt===selected),[slots,selected]);const dateLabel=useMemo(()=>new Intl.DateTimeFormat(locale==="ar"?"ar-TN":locale==="en"?"en-GB":"fr-TN",{weekday:"long",day:"numeric",month:"long",timeZone:"Africa/Tunis"}).format(new Date(`${selectedDate}T12:00:00+01:00`)),[locale,selectedDate]);
const time=(iso:string)=>new Intl.DateTimeFormat(locale==="ar"?"ar-TN":locale==="en"?"en-GB":"fr-TN",{hour:"2-digit",minute:"2-digit",timeZone:"Africa/Tunis"}).format(new Date(iso));
async function search(){setBusy(true);setError("");setSelected("");setSearched(false);try{const r=await fetch("/api/v1/availability/query",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({serviceId:service.id,fromDate:selectedDate,toDate:selectedDate,preferredPeriod:period||undefined})});const x=await jsonResponse(r);if(!r.ok)throw new Error("availability_failed");setSlots(Array.isArray(x.slots)?x.slots.filter((s:Slot)=>s.startAt.slice(0,10)===selectedDate):[]);setSearched(true)}catch{setSlots([]);setSearched(true);setError(c.searchError)}finally{setBusy(false)}}
async function confirm(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch("/api/v1/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({patientId:"patient-amal",serviceId:service.id,startAt:selected,idempotencyKey:`web-${service.id}-${selected}`,explicitConfirmation:true})});const x=await jsonResponse(r);if(!r.ok||!x.appointment?.id)throw new Error("appointment_failed");router.push(`/patient/appointments/${x.appointment.id}`);router.refresh()}catch{setError(c.confirmError)}finally{setBusy(false)}}
function resetResults(){setSlots([]);setSelected("");setSearched(false);setError("")}function changeDate(value:string){setSelectedDate(value);resetResults()}
return <div className="booking-flow"><div className="eyebrow">{c.eyebrow} · {service.name[locale]}</div><h1 className="mobile-title">{c.title}</h1><p className="muted booking-lead">{c.lead}</p><section className="booking-prep"><strong>{c.prep}</strong><ul><li>{c.id}</li><li>{c.rx}</li></ul><p>{c.note}</p></section><div className="form booking-form"><div className="field"><label>{c.date}</label><input className="input booking-date" type="date" min={datePlus(0)} value={selectedDate} onChange={e=>changeDate(e.target.value)}/></div><div className="field"><label>{c.preference}</label><div className="booking-periods"><button type="button" className={`slot ${period===""?"selected":""}`} onClick={()=>{setPeriod("");resetResults()}}>{c.allDay}</button><button type="button" className={`slot ${period==="morning"?"selected":""}`} onClick={()=>{setPeriod("morning");resetResults()}}>☀ {c.morning}</button><button type="button" className={`slot ${period==="afternoon"?"selected":""}`} onClick={()=>{setPeriod("afternoon");resetResults()}}>◐ {c.afternoon}</button></div></div><button className="btn btn-secondary btn-wide booking-search" disabled={busy||!selectedDate} onClick={search}>{busy?c.searching:c.show}</button>{error&&<div className="notice" role="alert">{error}</div>}{slots.length>0&&<section className="booking-slots"><div className="booking-slots-head"><div><div className="eyebrow">{c.available}</div><strong>{dateLabel}</strong></div><span className="badge good">{slots.length}</span></div><div className="slot-card-grid">{slots.map(s=>{const chosen=selected===s.startAt;return <button type="button" key={s.startAt} className={`time-card ${chosen?"selected":""}`} onClick={()=>setSelected(s.startAt)} aria-pressed={chosen}><span className="time-card-time">{time(s.startAt)}</span><span className="time-card-meta">{c.places(s.remaining)}</span>{chosen&&<span className="time-card-check">✓ {c.selected}</span>}</button>})}</div></section>}{searched&&!busy&&slots.length===0&&!error&&<div className="notice info">{c.none}</div>}{selectedSlot&&<section className="booking-summary" aria-live="polite"><div><div className="eyebrow">{c.summary}</div><strong className="booking-summary-date">{dateLabel}</strong><span className="booking-summary-time">{time(selectedSlot.startAt)}</span></div><button className="btn btn-primary" disabled={busy} onClick={confirm}>{busy?c.confirming:c.confirm}</button></section>}</div></div>}
