"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import {HeniAvatar} from "./HeniAvatar";
import {usePersistentLocale} from "@/lib/locale-client";

type Message={role:"heni"|"user";text:string;tool?:string};
type RecognitionLike={lang:string;interimResults:boolean;continuous:boolean;onstart:(()=>void)|null;onend:(()=>void)|null;onerror:((event:any)=>void)|null;onresult:((event:any)=>void)|null;start:()=>void;stop:()=>void;abort?:()=>void};

const copy={
fr:{hello:"Bonjour ! Je suis Heni. Je peux vous aider pour les rendez-vous, la préparation, le guidage et le suivi.",title:"Votre compagnon de parcours",online:"Assistant administratif",placeholder:"Écrivez ou parlez…",typed:"Écrivez votre demande…",close:"Fermer Heni",open:"Ouvrir Heni",send:"Envoyer",talk:"Parler à Heni",stop:"Arrêter l'écoute",safety:"Administratif & informationnel. Heni ne diagnostique pas et ne modifie aucun traitement.",startError:"Heni n'est pas disponible pour le moment. Veuillez réessayer.",chatError:"Je n'ai pas pu traiter votre message. Veuillez réessayer.",micUnsupported:"La saisie vocale n'est pas prise en charge par ce navigateur. Vous pouvez écrire votre demande.",micDenied:"L'accès au microphone a été refusé. Autorisez le micro dans le navigateur ou écrivez votre demande.",micEmpty:"Je n'ai rien entendu. Touchez le micro et réessayez.",listening:"Je vous écoute…",prompts:["Je veux un rendez-vous en imagerie","Que dois-je apporter au rendez-vous ?","Où se trouve l'imagerie ?","Je veux parler à un membre du personnel"]},
ar:{hello:"عسلامة! أنا هاني. نعاونك في الموعد، التحضير، الطريق والمتابعة.",title:"مرافقك في رحلة العلاج",online:"مساعد إداري",placeholder:"اكتب أو احكي…",typed:"اكتب طلبك…",close:"سكر هاني",open:"افتح هاني",send:"ابعث",talk:"احكي مع هاني",stop:"وقف الاستماع",safety:"هاني يساعد في الإدارة والمعلومات فقط. ما يشخّصش وما يبدّلش العلاج.",startError:"هاني موش متاح توّا. عاود حاول.",chatError:"ما نجمتش نعالج الرسالة. عاود حاول.",micUnsupported:"المتصفح هذا ما يدعمش الإدخال الصوتي. تنجم تكتب طلبك.",micDenied:"ما عناش إذن للميكرو. فعّل الميكرو من المتصفح ولا اكتب طلبك.",micEmpty:"ما سمعت حتى كلام. اضغط على الميكرو وعاود حاول.",listening:"نسمع فيك…",prompts:["نحب موعد في التصوير الطبي","شنوة نجيب للموعد؟","وين نمشي للتصوير الطبي؟","نحب نحكي مع موظف"]},
en:{hello:"Hi! I'm Heni. I can help with appointments, preparation, directions and follow-up.",title:"Your journey companion",online:"Administrative assistant",placeholder:"Type or speak…",typed:"Type your request…",close:"Close Heni",open:"Open Heni",send:"Send",talk:"Talk to Heni",stop:"Stop listening",safety:"Administrative and informational only. Heni does not diagnose or change treatment.",startError:"Heni is unavailable right now. Please try again.",chatError:"I couldn't process your message. Please try again.",micUnsupported:"Voice input is not supported in this browser. You can type your request.",micDenied:"Microphone access was denied. Allow microphone access or type your request.",micEmpty:"I didn't hear anything. Tap the microphone and try again.",listening:"I'm listening…",prompts:["I need an imaging appointment","What should I bring to my appointment?","Where is medical imaging?","I want to speak to staff"]}}

function browserSpeechRecognition(){if(typeof window==="undefined")return null;const w=window as typeof window&{SpeechRecognition?:new()=>RecognitionLike;webkitSpeechRecognition?:new()=>RecognitionLike};return w.SpeechRecognition??w.webkitSpeechRecognition??null}
async function safeJson(res:Response){const text=await res.text();if(!text)return{};try{return JSON.parse(text)}catch{throw new Error("invalid_json_response")}}

export function HeniCompanion(){
  const {locale,rtl}=usePersistentLocale();const c=copy[locale];
  const [open,setOpen]=useState(false);const [sessionId,setSessionId]=useState("");const [messages,setMessages]=useState<Message[]>([{role:"heni",text:c.hello}]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [speaking,setSpeaking]=useState(false);const [listening,setListening]=useState(false);const [micSupported,setMicSupported]=useState(true);const endRef=useRef<HTMLDivElement>(null);const mountedRef=useRef(true);const recognitionRef=useRef<RecognitionLike|null>(null);const busyRef=useRef(false);
  useEffect(()=>{mountedRef.current=true;setMicSupported(Boolean(browserSpeechRecognition()));return()=>{mountedRef.current=false;recognitionRef.current?.abort?.();if(typeof window!=="undefined"&&"speechSynthesis" in window)window.speechSynthesis.cancel()}},[]);
  useEffect(()=>{setSessionId("");setMessages([{role:"heni",text:c.hello}]);setInput("");recognitionRef.current?.abort?.();setListening(false)},[locale,c.hello]);
  useEffect(()=>{if(open)endRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[messages,open,busy]);

  const ensureSession=useCallback(async()=>{if(sessionId)return sessionId;const res=await fetch("/api/v1/voice/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale,patientId:"patient-amal",source:"floating_heni"})});const payload=await safeJson(res);if(!res.ok||!payload.session?.id)throw new Error("session_start_failed");if(mountedRef.current)setSessionId(payload.session.id);return payload.session.id as string},[sessionId,locale]);
  function speak(text:string){if(typeof window==="undefined"||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=locale==="ar"?"ar-TN":locale==="fr"?"fr-FR":"en-GB";utterance.rate=.93;const voices=window.speechSynthesis.getVoices();const wanted=voices.find(v=>v.lang.toLowerCase().startsWith(utterance.lang.toLowerCase().slice(0,2)));if(wanted)utterance.voice=wanted;utterance.onstart=()=>mountedRef.current&&setSpeaking(true);utterance.onend=()=>mountedRef.current&&setSpeaking(false);utterance.onerror=()=>mountedRef.current&&setSpeaking(false);window.speechSynthesis.speak(utterance)}
  const send=useCallback(async(rawText?:string)=>{const text=(rawText??input).trim();if(!text||busyRef.current)return;busyRef.current=true;setBusy(true);setInput("");setMessages(current=>[...current,{role:"user",text}]);try{let id=await ensureSession();let res=await fetch(`/api/v1/voice/session/${id}/turn`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})});let payload=await safeJson(res);if(res.status===404||String(payload.error??"").includes("Call session not found")){setSessionId("");const restart=await fetch("/api/v1/voice/session",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locale,patientId:"patient-amal",source:"floating_heni"})});const fresh=await safeJson(restart);if(!restart.ok||!fresh.session?.id)throw new Error("session_restart_failed");id=fresh.session.id;setSessionId(id);res=await fetch(`/api/v1/voice/session/${id}/turn`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text})});payload=await safeJson(res)}if(!res.ok)throw new Error("conversation_failed");const answer=String(payload.message??c.chatError);if(mountedRef.current)setMessages(current=>[...current,{role:"heni",text:answer,tool:payload.tool}]);speak(answer)}catch{if(mountedRef.current)setMessages(current=>[...current,{role:"heni",text:sessionId?c.chatError:c.startError}])}finally{busyRef.current=false;if(mountedRef.current)setBusy(false)}},[input,ensureSession,locale,c.chatError,c.startError,sessionId]);

  async function toggleListen(){if(listening){recognitionRef.current?.stop();return}const Recognition=browserSpeechRecognition();if(!Recognition){setMicSupported(false);setMessages(current=>[...current,{role:"heni",text:c.micUnsupported}]);return}try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(track=>track.stop())}const recognition=new Recognition();recognitionRef.current=recognition;recognition.lang=locale==="ar"?"ar-TN":locale==="fr"?"fr-FR":"en-GB";recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>setListening(true);recognition.onend=()=>{setListening(false);recognitionRef.current=null};recognition.onerror=(event:any)=>{setListening(false);recognitionRef.current=null;const denied=event?.error==="not-allowed"||event?.error==="service-not-allowed";setMessages(current=>[...current,{role:"heni",text:denied?c.micDenied:c.micEmpty}])};recognition.onresult=(event:any)=>{const transcript=String(event.results?.[0]?.[0]?.transcript??"").trim();if(!transcript){setMessages(current=>[...current,{role:"heni",text:c.micEmpty}]);return}setInput(transcript);void send(transcript)};recognition.start()}catch{setListening(false);setMessages(current=>[...current,{role:"heni",text:c.micDenied}])}}

  return <div className={`heni-companion ${open?"is-open":""} ${rtl?"rtl":""}`} dir={rtl?"rtl":"ltr"}>{open&&<section className="heni-panel" aria-label="Chat with Heni"><header className="heni-panel-head"><div className="row-start"><HeniAvatar size={58} speaking={speaking} listening={listening}/><div><div className="eyebrow">Heni · هاني</div><strong>{c.title}</strong><div className="heni-online"><span/> {c.online}</div></div></div><button className="icon-btn" onClick={()=>setOpen(false)} aria-label={c.close}>×</button></header><div className="heni-chat-log" aria-live="polite">{messages.map((message,index)=><div className={`heni-message ${message.role}`} key={`${message.role}-${index}`}>{message.text}{message.tool&&<div className="heni-tool">outil · {message.tool}</div>}</div>)}{busy&&<div className="heni-thinking" aria-label="Heni is typing"><span/><span/><span/></div>}{listening&&<div className="heni-recording-state"><span/> {c.listening}</div>}<div ref={endRef}/></div><div className="heni-quick-row">{c.prompts.map(prompt=><button key={prompt} onClick={()=>void send(prompt)} disabled={busy}>{prompt}</button>)}</div><div className="heni-compose"><button className={`heni-mic ${listening?"active":""}`} onClick={()=>void toggleListen()} disabled={busy} aria-label={listening?c.stop:c.talk}>{listening?"■":"🎙"}</button><input value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send()}}} placeholder={micSupported?c.placeholder:c.typed} aria-label="Message for Heni"/><button className="heni-send" onClick={()=>void send()} disabled={busy||!input.trim()} aria-label={c.send}>→</button></div><div className="heni-safety">{c.safety}</div></section>}<button className="heni-fab" onClick={()=>setOpen(value=>!value)} aria-expanded={open} aria-label={c.open}><HeniAvatar size={74} speaking={speaking} listening={listening}/>{!open&&<span className="heni-fab-label"><strong>Heni</strong><small>{locale==="ar"?"هاني معاك":locale==="en"?"I'm with you":"Je suis avec vous"}</small></span>}</button></div>
}
