"use client";
import Link from "next/link";
import {StaffShell} from "./StaffShell";
import {usePersistentLocale} from "@/lib/locale-client";
import {t} from "@/lib/i18n";
import {permissionGroups,roleMeta,rolePermissions,type Permission,type StaffRole} from "@/lib/access";

const permissionLabels:Record<Permission,{fr:string;ar:string;en:string}>={
"patients.view_general":{fr:"Voir les informations générales",ar:"عرض معلومات المريض العامة",en:"View general patient information"},"patients.edit_general":{fr:"Modifier les informations générales",ar:"تعديل المعلومات العامة",en:"Edit general patient information"},"patients.view_medical":{fr:"Voir le dossier médical",ar:"عرض الملف الطبي",en:"View medical record"},"patients.edit_medical":{fr:"Modifier les données cliniques",ar:"تعديل البيانات السريرية",en:"Edit clinical data"},"appointments.view":{fr:"Voir les rendez-vous",ar:"عرض المواعيد",en:"View appointments"},"appointments.create":{fr:"Créer un rendez-vous",ar:"إنشاء موعد",en:"Create appointments"},"appointments.edit":{fr:"Modifier un rendez-vous",ar:"تعديل موعد",en:"Edit appointments"},"appointments.cancel":{fr:"Annuler un rendez-vous",ar:"إلغاء موعد",en:"Cancel appointments"},"clinical_notes.view":{fr:"Voir les notes cliniques",ar:"عرض الملاحظات السريرية",en:"View clinical notes"},"clinical_notes.create":{fr:"Créer des notes cliniques",ar:"إضافة ملاحظات سريرية",en:"Create clinical notes"},"medical_documents.view":{fr:"Voir les documents médicaux",ar:"عرض الوثائق الطبية",en:"View medical documents"},"services.view":{fr:"Voir les services",ar:"عرض الخدمات",en:"View services"},"services.manage":{fr:"Gérer les services",ar:"إدارة الخدمات",en:"Manage services"},"schedules.view":{fr:"Voir les plannings",ar:"عرض الجداول",en:"View schedules"},"schedules.manage":{fr:"Gérer les plannings",ar:"إدارة الجداول",en:"Manage schedules"},"staff.view":{fr:"Voir les comptes équipe",ar:"عرض حسابات الفريق",en:"View staff accounts"},"staff.manage":{fr:"Gérer les comptes équipe",ar:"إدارة حسابات الفريق",en:"Manage staff accounts"},"roles.manage":{fr:"Gérer rôles et permissions",ar:"إدارة الأدوار والصلاحيات",en:"Manage roles and permissions"},"ai.manage":{fr:"Gérer IA / Hani",ar:"إدارة الذكاء الاصطناعي وهاني",en:"Manage AI / Hani"},"maps.manage":{fr:"Gérer cartes et navigation",ar:"إدارة الخرائط والملاحة",en:"Manage maps and navigation"},"translations.manage":{fr:"Gérer les traductions",ar:"إدارة الترجمات",en:"Manage translations"},"white_label.manage":{fr:"Gérer le white label",ar:"إدارة الهوية الخاصة",en:"Manage white label"},"notifications.manage":{fr:"Gérer les notifications",ar:"إدارة الإشعارات",en:"Manage notifications"},"integrations.manage":{fr:"Gérer les intégrations",ar:"إدارة التكاملات",en:"Manage integrations"},"analytics.view":{fr:"Voir les statistiques",ar:"عرض الإحصائيات",en:"View analytics"},"system_settings.manage":{fr:"Gérer les paramètres système",ar:"إدارة إعدادات النظام",en:"Manage system settings"},"audit.view":{fr:"Voir les journaux d'audit",ar:"عرض سجل التدقيق",en:"View audit logs"}};

export function RoleDetails({role}:{role:StaffRole}){const {locale}=usePersistentLocale();const meta=roleMeta[role];const allowed=new Set(rolePermissions[role]);return <StaffShell role={role}><div className="page-head"><div><div className="eyebrow">{t(locale,"permissions.title")}</div><h1>{t(locale,meta.labelKey)}</h1><p className="muted">{t(locale,meta.summaryKey)}</p></div><Link className="btn btn-secondary" href="/staff">← {t(locale,"common.back")}</Link></div><div className="permission-groups">{permissionGroups.map(([groupKey,permissions])=><section className="card permission-card" key={groupKey}><h3>{t(locale,groupKey)}</h3><div className="permission-list">{permissions.map(permission=>{const ok=allowed.has(permission);return <div className="permission-row" key={permission}><div><strong>{permissionLabels[permission][locale]}</strong><code>{permission}</code></div><span className={`badge ${ok?"good":""}`}>{ok?`✓ ${t(locale,"permissions.allowed")}`:`— ${t(locale,"permissions.denied")}`}</span></div>})}</div></section>)}</div></StaffShell>}
