"use client";
import Link from "next/link";
import {StaffShell} from "@/components/StaffShell";
import {usePersistentLocale} from "@/lib/locale-client";
import {t} from "@/lib/i18n";

const patients=[{name:"Amel Ben Salah",time:"09:30",service:"Imagerie médicale",status:"Confirmé"},{name:"Hédi Trabelsi",time:"11:00",service:"Consultation",status:"En attente"},{name:"Inès Mansour",time:"14:20",service:"Imagerie médicale",status:"Confirmé"}];

export default function DoctorDashboard(){const {locale}=usePersistentLocale();return <StaffShell role="doctor"><div className="page-head"><div><div className="eyebrow">{t(locale,"roles.doctor")}</div><h1>{t(locale,"doctor.dashboard")}</h1><p className="muted">{t(locale,"roles.doctor_summary")}</p></div><Link className="btn btn-secondary" href="/staff/roles/doctor">{t(locale,"staff.view_permissions")}</Link></div><div className="metric-grid"><div className="card metric"><div className="value">3</div><div className="label">{t(locale,"doctor.today")}</div></div><div className="card metric"><div className="value">2</div><div className="label">{t(locale,"doctor.notes")}</div></div><div className="card metric"><div className="value">1</div><div className="label">{t(locale,"doctor.results")}</div></div><div className="card metric"><div className="value">2</div><div className="label">{t(locale,"doctor.followups")}</div></div></div><div className="two-col" style={{marginTop:18}}><section className="card"><div className="row"><div><div className="eyebrow">{t(locale,"doctor.today")}</div><h3>{t(locale,"doctor.upcoming")}</h3></div><button className="btn btn-secondary">{t(locale,"common.search")}</button></div><div className="stack" style={{marginTop:14}}>{patients.map(p=><div className="clinical-row" key={p.name}><div><strong>{p.name}</strong><div className="muted tiny">{p.time} · {p.service}</div></div><span className="badge good">{p.status}</span></div>)}</div></section><section className="stack"><div className="card"><div className="eyebrow">{t(locale,"doctor.patient_search")}</div><h3>{t(locale,"doctor.patient_search")}</h3><input className="input" placeholder={t(locale,"common.search")}/></div><div className="card"><div className="eyebrow">{t(locale,"doctor.clinical_tasks")}</div><div className="task-list"><div><strong>{t(locale,"doctor.notes")}</strong><span>2</span></div><div><strong>{t(locale,"doctor.results")}</strong><span>1</span></div><div><strong>{t(locale,"doctor.followups")}</strong><span>2</span></div></div></div></section></div></StaffShell>}
