import type {Locale} from "./types";
import {t} from "./i18n";

type Dict=Record<string,string>;
const fr:Dict={
"heni.hello":"Bonjour ! Je suis Heni. Je peux vous aider pour les rendez-vous, la préparation, le guidage et le suivi.","heni.title":"Votre compagnon de parcours","heni.online":"Assistant administratif","heni.placeholder":"Écrivez ou parlez…","heni.typed":"Écrivez votre demande…","heni.close":"Fermer Heni","heni.open":"Ouvrir Heni","heni.send":"Envoyer","heni.talk":"Parler à Heni","heni.stop":"Arrêter l'écoute","heni.safety":"Administratif & informationnel. Heni ne diagnostique pas et ne modifie aucun traitement.","heni.start_error":"Heni n'est pas disponible pour le moment. Veuillez réessayer.","heni.chat_error":"Je n'ai pas pu traiter votre message. Veuillez réessayer.","heni.mic_unsupported":"La saisie vocale n'est pas prise en charge par ce navigateur. Vous pouvez écrire votre demande.","heni.mic_denied":"L'accès au microphone a été refusé. Autorisez le micro ou écrivez votre demande.","heni.mic_empty":"Je n'ai rien entendu. Touchez le micro et réessayez.","heni.listening":"Je vous écoute…","heni.with_you":"Je suis avec vous",
"heni.prompt1":"Je veux un rendez-vous en imagerie","heni.prompt2":"Que dois-je apporter au rendez-vous ?","heni.prompt3":"Où se trouve l'imagerie ?","heni.prompt4":"Je veux parler à un membre du personnel",
"voice.eyebrow":"Conversation Heni","voice.title":"Parlez naturellement à Heni.","voice.intro":"Utilisez le micro dans un navigateur compatible ou écrivez votre message. Les actions passent par les mêmes outils administratifs que l'application.","voice.connect":"connexion","voice.ready":"prêt","voice.listen":"j'écoute","voice.process":"je traite","voice.speak":"je parle","voice.assistant":"Assistant patient administratif","voice.stop":"Arrêter","voice.talk":"Parlez","voice.micro":"Tunisien / Français","voice.unsupported":"Micro non supporté","voice.auto":"Réponse vocale automatique","voice.placeholder":"Écrivez ou parlez…","voice.send":"Envoyer","voice.new":"Nouvelle conversation","voice.trace":"Voir la trace outils",
"map.location_start":"Point de départ : entrée principale du scénario","map.location_unavailable":"La géolocalisation n'est pas disponible. Le mode démo utilise l'entrée principale.","map.location_near":"Position détectée près du site. L'étape intérieure démarre à l'entrée principale.","map.location_far":"Vous n'êtes pas sur le site de démonstration. Le parcours démarre à l'entrée principale de Charles Nicolle.","map.location_denied":"Position non autorisée. Le scénario démarre à l'entrée principale.","map.outdoor":"Contexte extérieur réel","map.optional":"optionnel","map.open_outdoor":"Voir le contexte extérieur ↗","map.smart_start":"Point de départ intelligent","map.floor":"Niveau","map.minutes":"min","map.site":"Hôpital Charles Nicolle · site de démonstration","map.address":"Hôpital Charles Nicolle · Boulevard 9 Avril 1938, Tunis",
"landing.presentation":"Mode présentation","landing.staff":"Console équipe","landing.start":"Démarrer la démo","landing.eyebrow":"Future Health Connectathon · Tunis 2026","landing.title":"De « j'ai besoin de soins » à « je sais ce qui vient ensuite ».","landing.lead":"Hani Maak — هاني معاك relie l'accès, le guidage à l'hôpital et la continuité via le mobile, la voix et un même backend opérationnel.","landing.patient":"Démarrer le parcours patient","landing.talk":"Parler à Heni","landing.guidance":"Voir le guidage hôpital","landing.multi":"Un parcours · plusieurs interfaces","landing.not_app":"Pas une simple application de rendez-vous.","landing.access":"Accès","landing.access_body":"Créneaux issus des règles, confirmation, annulation et déplacement via mobile ou conversation.","landing.guidance_title":"Guidage","landing.guidance_body":"Préparation, graphe de trajet déterministe et démonstration AR vers le service.","landing.continuity":"Continuité","landing.continuity_body":"Instructions validées, rappels, prochaines étapes et visibilité opérationnelle.","landing.footer":"Hani Maak · environnement synthétique de compétition · pas un système de décision clinique",
"present.title":"Une histoire patient. Huit preuves.","present.lead":"Chaque carte ouvre une surface fonctionnelle. La séquence forte : accès → trajet → AR → voix → trace équipe → continuité.","present.home":"Accueil","present.voice":"Preuve voix","present.close":"Hani Maak n'est pas une application de rendez-vous. C'est la couche qui accompagne le patient de l'accès au guidage puis à la continuité."
};
const en:Dict={...fr,
"heni.hello":"Hi! I'm Heni. I can help with appointments, preparation, directions and follow-up.","heni.title":"Your journey companion","heni.online":"Administrative assistant","heni.placeholder":"Type or speak…","heni.typed":"Type your request…","heni.close":"Close Heni","heni.open":"Open Heni","heni.send":"Send","heni.talk":"Talk to Heni","heni.stop":"Stop listening","heni.safety":"Administrative and informational only. Heni does not diagnose or change treatment.","heni.start_error":"Heni is unavailable right now. Please try again.","heni.chat_error":"I couldn't process your message. Please try again.","heni.mic_unsupported":"Voice input is not supported in this browser. You can type your request.","heni.mic_denied":"Microphone access was denied. Allow it or type your request.","heni.mic_empty":"I didn't hear anything. Tap the microphone and try again.","heni.listening":"I'm listening…","heni.with_you":"I'm with you","heni.prompt1":"I need an imaging appointment","heni.prompt2":"What should I bring to my appointment?","heni.prompt3":"Where is medical imaging?","heni.prompt4":"I want to speak to staff",
"voice.eyebrow":"Heni conversation","voice.title":"Talk naturally with Heni.","voice.intro":"Use the microphone in a compatible browser or type your message. Actions use the same administrative tools as the app.","voice.connect":"connecting","voice.ready":"ready","voice.listen":"listening","voice.process":"processing","voice.speak":"speaking","voice.assistant":"Patient administrative assistant","voice.stop":"Stop","voice.talk":"Speak","voice.micro":"Arabic / French / English","voice.unsupported":"Microphone unsupported","voice.auto":"Speak replies automatically","voice.placeholder":"Type or speak…","voice.send":"Send","voice.new":"New conversation","voice.trace":"View tool trace",
"map.location_start":"Starting point: main scenario entrance","map.location_unavailable":"Geolocation is unavailable. Demo mode uses the main entrance.","map.location_near":"Position detected near the site. Indoor guidance starts at the main entrance.","map.location_far":"You are not on the demonstration site. The route starts at Charles Nicolle's main entrance.","map.location_denied":"Location access denied. The scenario starts at the main entrance.","map.outdoor":"Real outdoor context","map.optional":"optional","map.open_outdoor":"View outdoor context ↗","map.smart_start":"Smart starting point","map.floor":"Level","map.minutes":"min","map.site":"Charles Nicolle Hospital · demonstration site","map.address":"Charles Nicolle Hospital · Boulevard 9 Avril 1938, Tunis",
"landing.presentation":"Presentation mode","landing.staff":"Staff console","landing.start":"Start demo","landing.eyebrow":"Future Health Connectathon · Tunis 2026","landing.title":"From “I need care” to “I know what comes next.”","landing.lead":"Hani Maak — هاني معاك connects access, hospital guidance and continuity through mobile, voice and one shared operational backend.","landing.patient":"Start patient journey","landing.talk":"Talk to Heni","landing.guidance":"See hospital guidance","landing.multi":"One journey · multiple interfaces","landing.not_app":"Not another appointment app.","landing.access":"Access","landing.access_body":"Rule-derived slots, confirmation, cancellation and rescheduling through mobile or conversation.","landing.guidance_title":"Guidance","landing.guidance_body":"Preparation, deterministic route graph and AR demonstration toward the service.","landing.continuity":"Continuity","landing.continuity_body":"Verified instructions, reminders, next steps and operational visibility.","landing.footer":"Hani Maak · synthetic competition environment · not a clinical decision system",
"present.title":"One patient story. Eight proof points.","present.lead":"Every card opens a working surface. Strong sequence: access → route → AR → voice → staff trace → continuity.","present.home":"Home","present.voice":"Voice proof","present.close":"Hani Maak is not an appointment app. It is the layer that stays with the patient from access to guidance to continuity."
};
const ar:Dict={...en,
"heni.hello":"عسلامة! أنا هاني. نعاونك في الموعد، التحضير، الطريق والمتابعة.","heni.title":"مرافقك في رحلة العلاج","heni.online":"مساعد إداري","heni.placeholder":"اكتب أو احكي…","heni.typed":"اكتب طلبك…","heni.close":"سكر هاني","heni.open":"افتح هاني","heni.send":"ابعث","heni.talk":"احكي مع هاني","heni.stop":"وقف الاستماع","heni.safety":"هاني يساعد في الإدارة والمعلومات فقط. ما يشخّصش وما يبدّلش العلاج.","heni.start_error":"هاني موش متاح توّا. عاود حاول.","heni.chat_error":"ما نجمتش نعالج الرسالة. عاود حاول.","heni.mic_unsupported":"المتصفح هذا ما يدعمش الإدخال الصوتي. تنجم تكتب طلبك.","heni.mic_denied":"ما عناش إذن للميكرو. فعّلو ولا اكتب طلبك.","heni.mic_empty":"ما سمعت حتى كلام. اضغط على الميكرو وعاود حاول.","heni.listening":"نسمع فيك…","heni.with_you":"هاني معاك","heni.prompt1":"نحب موعد في التصوير الطبي","heni.prompt2":"شنوة نجيب للموعد؟","heni.prompt3":"وين نمشي للتصوير الطبي؟","heni.prompt4":"نحب نحكي مع موظف",
"voice.eyebrow":"محادثة هاني","voice.title":"احكي مع هاني بطبيعتك.","voice.intro":"استعمل الميكرو إذا المتصفح يدعمو، ولا اكتب رسالتك. هاني يستعمل نفس الأدوات الإدارية متاع التطبيق.","voice.connect":"اتصال","voice.ready":"حاضر","voice.listen":"نسمع","voice.process":"نعالج","voice.speak":"نحكي","voice.assistant":"مساعد إداري للمريض","voice.stop":"وقف","voice.talk":"احكي","voice.micro":"تونسي / فرنسي","voice.unsupported":"الميكرو غير مدعوم","voice.auto":"اقرا الرد بالصوت","voice.placeholder":"اكتب أو احكي…","voice.send":"ابعث","voice.new":"محادثة جديدة","voice.trace":"شوف سجل الأدوات",
"map.location_start":"نقطة البداية: المدخل الرئيسي","map.location_unavailable":"تحديد الموقع موش متاح. الديمو يبدأ من المدخل الرئيسي.","map.location_near":"الموقع قريب من المستشفى. التوجيه الداخلي يبدأ من المدخل الرئيسي.","map.location_far":"إنت موش في موقع الديمو. المسار يبدأ من المدخل الرئيسي لشارل نيكول.","map.location_denied":"ما عناش إذن للموقع. المسار يبدأ من المدخل الرئيسي.","map.outdoor":"الموقع الخارجي الحقيقي","map.optional":"اختياري","map.open_outdoor":"شوف الموقع الخارجي ↗","map.smart_start":"نقطة بداية ذكية","map.floor":"الطابق","map.minutes":"دق","map.site":"مستشفى شارل نيكول · موقع الديمو","map.address":"مستشفى شارل نيكول · شارع 9 أفريل 1938، تونس",
"landing.presentation":"وضع العرض","landing.staff":"فضاء الفريق","landing.start":"ابدأ الديمو","landing.eyebrow":"Future Health Connectathon · تونس 2026","landing.title":"من «نحتاج رعاية» إلى «نعرف شنوّة الخطوة الجاية».","landing.lead":"هاني معاك يربط الوصول، التوجيه داخل المستشفى والمتابعة عبر الهاتف، الصوت ونفس النظام التشغيلي.","landing.patient":"ابدأ مسار المريض","landing.talk":"احكي مع هاني","landing.guidance":"شوف توجيه المستشفى","landing.multi":"مسار واحد · واجهات متعددة","landing.not_app":"موش مجرد تطبيق مواعيد.","landing.access":"الوصول","landing.access_body":"مواعيد محسوبة بالقواعد، تأكيد وإلغاء وتغيير عبر التطبيق أو المحادثة.","landing.guidance_title":"التوجيه","landing.guidance_body":"تحضير، مسار ثابت وتجربة AR للوصول للمصلحة.","landing.continuity":"المتابعة","landing.continuity_body":"تعليمات مثبتة، تذكير، خطوات جاية ورؤية تشغيلية.","landing.footer":"هاني معاك · بيئة مسابقة ببيانات اصطناعية · موش نظام قرار سريري",
"present.title":"قصة مريض واحدة. ثمانية براهين.","present.lead":"كل بطاقة تفتح واجهة تخدم. التسلسل الأقوى: الوصول → الطريق → AR → الصوت → سجل الفريق → المتابعة.","present.home":"الرئيسية","present.voice":"تجربة الصوت","present.close":"هاني معاك موش تطبيق مواعيد. هو الطبقة اللي تبقى مع المريض من الوصول للتوجيه للمتابعة."
};
const all:Record<Locale,Dict>={fr,en,ar};
export function tx(locale:Locale,key:string,fallback?:string){return all[locale][key]??all.fr[key]??t(locale,key,fallback)}
