import type { Locale } from "./types";

type Dictionary=Record<string,string>;

export const dictionaries:Record<Locale,Dictionary>={
  fr:{
    "common.save":"Enregistrer","common.cancel":"Annuler","common.view":"Voir","common.manage":"Gérer","common.search":"Rechercher","common.back":"Retour","common.access_denied":"Vous n'avez pas l'autorisation d'accéder à cette section.",
    "nav.home":"Accueil","nav.journey":"Parcours","nav.map":"Plan","nav.profile":"Profil","nav.overview":"Vue d'ensemble","nav.appointments":"Rendez-vous","nav.patients":"Patients","nav.services":"Services","nav.calls":"Appels & Hani","nav.analytics":"Analytique","nav.settings":"Paramètres","nav.roles":"Rôles & permissions","nav.accounts":"Comptes","nav.white_label":"White label",
    "patient.next":"Votre prochaine étape","patient.book":"Prendre un rendez-vous","patient.guide":"Guide-moi","patient.call":"Appeler Hani Maak","patient.help":"Besoin d'aide","patient.prototype":"Itinéraire prototype — non validé par l'hôpital",
    "staff.title":"Console équipe","staff.subtitle":"Choisissez l'espace adapté à votre responsabilité.","staff.role_overview":"Niveaux d'accès","staff.what_can_access":"Informations accessibles","staff.what_can_manage":"Peut gérer","staff.open_workspace":"Ouvrir l'espace","staff.view_permissions":"Voir les permissions",
    "roles.doctor":"Médecin","roles.doctor_summary":"Soins cliniques et informations médicales nécessaires au traitement.","roles.administration":"Administration","roles.administration_summary":"Rendez-vous, planning et opérations patient sans accès clinique complet.","roles.super_admin":"Super Admin / White Label","roles.super_admin_summary":"Configuration de la plateforme, IA, comptes, langues, intégrations et marque.",
    "roles.doctor_access":"Données patient générales et cliniques, documents médicaux, rendez-vous et notes.","roles.doctor_manage":"Notes cliniques, instructions, contexte de rendez-vous et suivi médical.","roles.administration_access":"Identité générale, coordonnées, rendez-vous, services et planning.","roles.administration_manage":"Rendez-vous, planning, services et opérations quotidiennes.","roles.super_admin_access":"Configuration technique, comptes, rôles, IA, cartes, langues et statistiques.","roles.super_admin_manage":"Paramètres globaux, permissions, marque blanche, intégrations et fonctionnalités.",
    "permissions.title":"Matrice des permissions","permissions.patient_data":"Données patient","permissions.appointments":"Rendez-vous","permissions.clinical":"Clinique","permissions.operations":"Opérations","permissions.platform":"Plateforme","permissions.allowed":"Autorisé","permissions.denied":"Restreint",
    "doctor.dashboard":"Espace médecin","doctor.today":"Aujourd'hui","doctor.upcoming":"Rendez-vous à venir","doctor.patient_search":"Recherche patient","doctor.clinical_tasks":"Tâches cliniques","doctor.notes":"Notes à compléter","doctor.results":"Résultats à revoir","doctor.followups":"Suivis",
    "administration.dashboard":"Espace administration","administration.today":"Opérations du jour","administration.quick_actions":"Actions rapides","administration.new_appointment":"Nouveau rendez-vous","administration.manage_schedule":"Gérer le planning","administration.checkin":"Enregistrer l'arrivée",
    "super.dashboard":"Super Admin / White Label","super.platform":"Plateforme","super.ai":"IA / Hani","super.navigation":"Navigation","super.access":"Accès","super.system":"Système","super.organizations":"Organisations & marque blanche","super.languages":"Langues","super.features":"Fonctionnalités","super.integrations":"Intégrations","super.logs":"Journaux d'audit",
    "accounts.title":"Gestion des comptes","accounts.name":"Nom","accounts.email":"E-mail","accounts.role":"Rôle","accounts.department":"Service","accounts.status":"Statut","accounts.last_login":"Dernière connexion","accounts.created":"Créé le","accounts.active":"Actif","accounts.inactive":"Inactif"
  },
  ar:{
    "common.save":"حفظ","common.cancel":"إلغاء","common.view":"عرض","common.manage":"إدارة","common.search":"بحث","common.back":"رجوع","common.access_denied":"ما عندكش صلاحية للدخول للقسم هذا.",
    "nav.home":"الرئيسية","nav.journey":"مساري","nav.map":"الخريطة","nav.profile":"حسابي","nav.overview":"نظرة عامة","nav.appointments":"المواعيد","nav.patients":"المرضى","nav.services":"الخدمات","nav.calls":"المكالمات وهاني","nav.analytics":"الإحصائيات","nav.settings":"الإعدادات","nav.roles":"الأدوار والصلاحيات","nav.accounts":"الحسابات","nav.white_label":"الهوية الخاصة",
    "patient.next":"خطوتك القادمة","patient.book":"احجز موعداً","patient.guide":"دلّني","patient.call":"اتصل بهاني معاك","patient.help":"تحتاج مساعدة؟","patient.prototype":"مسار تجريبي — غير معتمد من المستشفى",
    "staff.title":"فضاء الفريق","staff.subtitle":"اختار الفضاء المناسب حسب مسؤوليتك.","staff.role_overview":"مستويات النفاذ","staff.what_can_access":"المعلومات المتاحة","staff.what_can_manage":"ما يمكن إدارته","staff.open_workspace":"افتح الفضاء","staff.view_permissions":"شوف الصلاحيات",
    "roles.doctor":"طبيب","roles.doctor_summary":"رعاية سريرية ونفاذ للمعلومات الطبية اللازمة للعلاج.","roles.administration":"الإدارة","roles.administration_summary":"المواعيد والجدولة وعمليات المرضى دون نفاذ كامل للبيانات السريرية.","roles.super_admin":"المشرف العام / White Label","roles.super_admin_summary":"إعداد المنصة والذكاء الاصطناعي والحسابات واللغات والتكاملات والهوية.",
    "roles.doctor_access":"بيانات عامة وسريرية للمريض، وثائق طبية، مواعيد وملاحظات.","roles.doctor_manage":"ملاحظات سريرية، تعليمات، سياق الموعد والمتابعة الطبية.","roles.administration_access":"الهوية العامة، الاتصال، المواعيد، الخدمات والجدولة.","roles.administration_manage":"المواعيد، الجداول، الخدمات والعمليات اليومية.","roles.super_admin_access":"الإعداد التقني، الحسابات، الأدوار، الذكاء الاصطناعي، الخرائط، اللغات والإحصائيات.","roles.super_admin_manage":"الإعدادات العامة، الصلاحيات، الهوية الخاصة، التكاملات والميزات.",
    "permissions.title":"مصفوفة الصلاحيات","permissions.patient_data":"بيانات المريض","permissions.appointments":"المواعيد","permissions.clinical":"السريري","permissions.operations":"العمليات","permissions.platform":"المنصة","permissions.allowed":"مسموح","permissions.denied":"مقيّد",
    "doctor.dashboard":"فضاء الطبيب","doctor.today":"اليوم","doctor.upcoming":"المواعيد القادمة","doctor.patient_search":"بحث عن مريض","doctor.clinical_tasks":"مهام سريرية","doctor.notes":"ملاحظات ناقصة","doctor.results":"نتائج للمراجعة","doctor.followups":"متابعة",
    "administration.dashboard":"فضاء الإدارة","administration.today":"عمليات اليوم","administration.quick_actions":"إجراءات سريعة","administration.new_appointment":"موعد جديد","administration.manage_schedule":"إدارة الجدول","administration.checkin":"تسجيل وصول المريض",
    "super.dashboard":"المشرف العام / White Label","super.platform":"المنصة","super.ai":"الذكاء الاصطناعي / هاني","super.navigation":"الملاحة","super.access":"النفاذ","super.system":"النظام","super.organizations":"المؤسسات والهوية","super.languages":"اللغات","super.features":"الميزات","super.integrations":"التكاملات","super.logs":"سجل التدقيق",
    "accounts.title":"إدارة الحسابات","accounts.name":"الاسم","accounts.email":"البريد الإلكتروني","accounts.role":"الدور","accounts.department":"القسم","accounts.status":"الحالة","accounts.last_login":"آخر دخول","accounts.created":"تاريخ الإنشاء","accounts.active":"نشط","accounts.inactive":"غير نشط"
  },
  en:{
    "common.save":"Save","common.cancel":"Cancel","common.view":"View","common.manage":"Manage","common.search":"Search","common.back":"Back","common.access_denied":"You do not have permission to access this section.",
    "nav.home":"Home","nav.journey":"Journey","nav.map":"Map","nav.profile":"Profile","nav.overview":"Overview","nav.appointments":"Appointments","nav.patients":"Patients","nav.services":"Services","nav.calls":"Calls & Hani","nav.analytics":"Analytics","nav.settings":"Settings","nav.roles":"Roles & permissions","nav.accounts":"Accounts","nav.white_label":"White label",
    "patient.next":"Your next step","patient.book":"Book an appointment","patient.guide":"Guide me","patient.call":"Call Hani Maak","patient.help":"Need help","patient.prototype":"Prototype route — not validated by the hospital",
    "staff.title":"Staff Console","staff.subtitle":"Choose the workspace that matches your responsibility.","staff.role_overview":"Access levels","staff.what_can_access":"Information available","staff.what_can_manage":"Can manage","staff.open_workspace":"Open workspace","staff.view_permissions":"View permissions",
    "roles.doctor":"Doctor","roles.doctor_summary":"Clinical care and the medical information required for treatment.","roles.administration":"Administration","roles.administration_summary":"Appointments, scheduling and patient operations without full clinical access.","roles.super_admin":"Super Admin / White Label","roles.super_admin_summary":"Platform, AI, accounts, languages, integrations and branding configuration.",
    "roles.doctor_access":"General and clinical patient data, medical documents, appointments and notes.","roles.doctor_manage":"Clinical notes, instructions, appointment context and follow-up.","roles.administration_access":"General identity, contact details, appointments, services and schedules.","roles.administration_manage":"Appointments, schedules, services and daily operations.","roles.super_admin_access":"Technical configuration, accounts, roles, AI, maps, languages and analytics.","roles.super_admin_manage":"Global settings, permissions, white-label configuration, integrations and features.",
    "permissions.title":"Permission matrix","permissions.patient_data":"Patient data","permissions.appointments":"Appointments","permissions.clinical":"Clinical","permissions.operations":"Operations","permissions.platform":"Platform","permissions.allowed":"Allowed","permissions.denied":"Restricted",
    "doctor.dashboard":"Doctor workspace","doctor.today":"Today","doctor.upcoming":"Upcoming appointments","doctor.patient_search":"Patient search","doctor.clinical_tasks":"Clinical tasks","doctor.notes":"Notes to complete","doctor.results":"Results to review","doctor.followups":"Follow-ups",
    "administration.dashboard":"Administration workspace","administration.today":"Today's operations","administration.quick_actions":"Quick actions","administration.new_appointment":"New appointment","administration.manage_schedule":"Manage schedule","administration.checkin":"Check in patient",
    "super.dashboard":"Super Admin / White Label","super.platform":"Platform","super.ai":"AI / Hani","super.navigation":"Navigation","super.access":"Access","super.system":"System","super.organizations":"Organizations & white label","super.languages":"Languages","super.features":"Features","super.integrations":"Integrations","super.logs":"Audit logs",
    "accounts.title":"Account management","accounts.name":"Name","accounts.email":"Email","accounts.role":"Role","accounts.department":"Department","accounts.status":"Status","accounts.last_login":"Last login","accounts.created":"Created","accounts.active":"Active","accounts.inactive":"Inactive"
  }
};

export function t(locale:Locale,key:string,fallback?:string){return dictionaries[locale][key]??dictionaries.fr[key]??fallback??key}

export const text={
  fr:{home:t("fr","nav.home"),journey:t("fr","nav.journey"),map:t("fr","nav.map"),profile:t("fr","nav.profile"),next:t("fr","patient.next"),book:t("fr","patient.book"),guide:t("fr","patient.guide"),call:t("fr","patient.call"),help:t("fr","patient.help"),prototype:t("fr","patient.prototype")},
  ar:{home:t("ar","nav.home"),journey:t("ar","nav.journey"),map:t("ar","nav.map"),profile:t("ar","nav.profile"),next:t("ar","patient.next"),book:t("ar","patient.book"),guide:t("ar","patient.guide"),call:t("ar","patient.call"),help:t("ar","patient.help"),prototype:t("ar","patient.prototype")},
  en:{home:t("en","nav.home"),journey:t("en","nav.journey"),map:t("en","nav.map"),profile:t("en","nav.profile"),next:t("en","patient.next"),book:t("en","patient.book"),guide:t("en","patient.guide"),call:t("en","patient.call"),help:t("en","patient.help"),prototype:t("en","patient.prototype")}
};
