import type {Locale} from "./types";

type Dictionary=Record<string,string>;
const fr:Dictionary={
"common.save":"Enregistrer","common.cancel":"Annuler","common.confirm":"Confirmer","common.view":"Voir","common.manage":"Gérer","common.search":"Rechercher","common.back":"Retour","common.edit":"Modifier","common.create":"Créer","common.close":"Fermer","common.loading":"Chargement…","common.active":"Actif","common.inactive":"Inactif","common.yes":"Oui","common.no":"Non","common.access_denied":"Vous n'avez pas l'autorisation d'accéder à cette section.","common.access_denied_hint":"Revenez à la console équipe et ouvrez un espace correspondant à votre rôle.","common.synthetic":"Données synthétiques","common.status":"Statut","common.action":"Action","common.time":"Heure","common.channel":"Canal","common.patient":"Patient","common.service":"Service",
"nav.home":"Accueil","nav.journey":"Parcours","nav.map":"Plan","nav.profile":"Profil","nav.overview":"Vue d'ensemble","nav.appointments":"Rendez-vous","nav.patients":"Patients","nav.services":"Services","nav.calls":"Appels & Hani","nav.analytics":"Analytique","nav.settings":"Paramètres","nav.roles":"Rôles & permissions","nav.accounts":"Comptes","nav.white_label":"White label","nav.audit":"Journal d'audit","nav.notifications":"Notifications","nav.integrations":"Intégrations",
"patient.navigation":"Navigation patient","patient.hello":"Bonjour","patient.with_you":"Je suis avec vous.","patient.simple_lead":"Une seule prochaine étape, sans tableau de bord compliqué.","patient.next":"Votre prochaine étape","patient.your_appointment":"Votre rendez-vous","patient.organize_visit":"Organiser votre visite","patient.organize_hint":"Trouvez le service et choisissez un horaire disponible.","patient.book":"Prendre un rendez-vous","patient.continue":"Continuer le parcours","patient.guide":"Guide-moi","patient.talk":"Parler","patient.journey_glance":"Votre parcours en un coup d'œil","patient.progress":"Progression","patient.no_journey":"Pas encore de parcours actif","patient.no_journey_hint":"Un parcours sera créé automatiquement après votre réservation.","patient.phone_preference":"Vous préférez téléphoner ?","patient.phone_hint":"Même logique, même disponibilité, interface vocale.","patient.try":"Essayer","patient.call":"Appeler Hani Maak","patient.help":"Besoin d'aide","patient.prototype":"Itinéraire prototype — non validé par l'hôpital",
"services.eyebrow":"Accès","services.title":"De quel service avez-vous besoin ?","services.hint":"Choisissez un service pour passer directement au choix du rendez-vous.",
"booking.eyebrow":"Rendez-vous","booking.title":"Quand préférez-vous venir ?","booking.lead":"Choisissez d'abord une date, puis une heure disponible.","booking.date":"Date","booking.preference":"Préférence","booking.morning":"Matin","booking.afternoon":"Après-midi","booking.all_day":"Toute la journée","booking.show":"Voir les créneaux disponibles","booking.searching":"Recherche…","booking.available":"Heures disponibles","booking.none":"Aucun créneau disponible pour cette date.","booking.place":"place","booking.places":"places","booking.summary":"Votre rendez-vous","booking.confirm":"Confirmer ce rendez-vous","booking.confirming":"Confirmation…","booking.selected":"Sélectionné","booking.prep":"À prévoir pour votre rendez-vous","booking.id":"Pièce d'identité","booking.rx":"Ordonnance ou demande médicale si disponible","booking.note":"Les consignes spécifiques à l'examen seront communiquées ou confirmées par le professionnel de santé.","booking.search_error":"Impossible de charger les créneaux. Veuillez réessayer.","booking.confirm_error":"Une erreur est survenue lors de la confirmation. Veuillez réessayer.",
"appointment.confirmed":"Rendez-vous confirmé","appointment.reserved":"C'est réservé.","appointment.journey_created":"Votre parcours a été créé automatiquement avec préparation, navigation, visite et suivi.","appointment.view_journey":"Voir mon parcours","appointment.view_route":"Voir l'itinéraire prototype","appointment.move":"Déplacer le rendez-vous","appointment.new_slots":"Nouveaux créneaux","appointment.confirm_move":"Confirmer le déplacement","appointment.cancel":"Annuler le rendez-vous","appointment.cancel_confirm":"Annuler ce rendez-vous ?","appointment.waitlist":"M'avertir si un créneau plus tôt se libère","appointment.waitlist_added":"Vous êtes sur la liste d'alerte pour un créneau plus tôt.",
"journey.eyebrow":"Continuité","journey.title":"Votre parcours","journey.lead":"Une chronologie simple : ce qui est terminé, ce qui vient maintenant et ce qui viendra après.","journey.empty":"Aucun parcours actif","journey.empty_hint":"Prenez un rendez-vous pour démarrer.","journey.understood":"J'ai compris","journey.updating":"Mise à jour…","journey.open_guidance":"Ouvrir le guidage",
"profile.title":"Profil","profile.language":"Langue","profile.channel":"Canal préféré","profile.data":"Données","profile.medicine":"Relire un emballage de médicament","profile.voice":"Tester l'assistant vocal","profile.caregiver":"Autoriser un proche","profile.caregiver_hint":"Prototype de délégation pour rendez-vous, parcours et rappels.","profile.caregiver_name":"Nom du proche","profile.phone":"Téléphone","profile.authorize":"Autoriser ce proche","profile.delegated":"Accès délégué dans le prototype.","profile.active_delegations":"délégation(s) active(s) dans la démo.","profile.production_note":"En production, les permissions, consentements et délégations aidant/proche seront gérés ici. Le concours utilise uniquement des identités synthétiques.",
"map.eyebrow":"Guidage · Charles Nicolle","map.title":"Je vous guide jusqu'au service.","map.lead":"Le trajet est calculé par un graphe déterministe. La couche intérieure est explicitement un prototype.","map.prototype":"Route prototype — campus intérieur non validé par l'hôpital.","map.real_context":"Contexte réel","map.position":"Ma position","map.ar":"Mode AR","map.step":"Étape","map.remaining":"m restants","map.start":"Commencez à l'entrée principale puis suivez la ligne Hani Maak.","map.continue":"Continuez vers la destination.","map.accessible":"Parcours accessible","map.deterministic":"Guidage déterministe","map.arrived":"Je suis arrivé à ce point","map.destination":"Destination atteinte.","map.unavailable":"Guidage indisponible.",
"medicine.eyebrow":"Continuité · Prototype vision","medicine.title":"Relire mon médicament","medicine.lead":"Clarifiez le texte visible d'un emballage déjà en votre possession et retrouvez une instruction professionnelle enregistrée.","medicine.safety":"Cette fonction aide à relire l'emballage et à retrouver une instruction enregistrée. Elle ne décide pas si vous devez prendre le médicament et ne change jamais la dose.","medicine.choose":"Photographier ou choisir l'emballage","medicine.read":"Lire le texte visible","medicine.analyzing":"Analyse…","medicine.detected":"Texte détecté — à confirmer","medicine.name_unknown":"Nom non détecté","medicine.strength":"Force","medicine.date":"Date visible","medicine.lot":"Lot","medicine.unknown":"inconnue","medicine.not_detected":"non détectée","medicine.instruction":"Instruction professionnelle enregistrée — démo","medicine.expired":"La date détectée est passée. Contactez un pharmacien ou le professionnel de santé; n'utilisez pas cette information seule pour décider quoi faire.","medicine.not_expired":"La date visible détectée n'est pas passée. Cela ne permet pas de conclure que le médicament est adapté ou sûr à utiliser.",
"staff.title":"Console équipe","staff.subtitle":"Choisissez l'espace adapté à votre responsabilité.","staff.role_overview":"Niveaux d'accès","staff.what_can_access":"Informations accessibles","staff.what_can_manage":"Peut gérer","staff.open_workspace":"Ouvrir l'espace","staff.view_permissions":"Voir les permissions",
"roles.doctor":"Médecin","roles.doctor_summary":"Soins cliniques et informations médicales nécessaires au traitement.","roles.administration":"Administration","roles.administration_summary":"Rendez-vous, planning et opérations patient sans accès clinique complet.","roles.super_admin":"Super Admin / White Label","roles.super_admin_summary":"Configuration de la plateforme, IA, comptes, langues, intégrations et marque.","roles.doctor_access":"Données patient générales et cliniques, documents médicaux, rendez-vous et notes.","roles.doctor_manage":"Notes cliniques, instructions, contexte de rendez-vous et suivi médical.","roles.administration_access":"Identité générale, coordonnées, rendez-vous, services et planning.","roles.administration_manage":"Rendez-vous, planning, services et opérations quotidiennes.","roles.super_admin_access":"Configuration technique, comptes, rôles, IA, cartes, langues et statistiques.","roles.super_admin_manage":"Paramètres globaux, permissions, marque blanche, intégrations et fonctionnalités.",
"permissions.title":"Matrice des permissions","permissions.patient_data":"Données patient","permissions.appointments":"Rendez-vous","permissions.clinical":"Clinique","permissions.operations":"Opérations","permissions.platform":"Plateforme","permissions.allowed":"Autorisé","permissions.denied":"Restreint",
"doctor.dashboard":"Espace médecin","doctor.today":"Aujourd'hui","doctor.upcoming":"Rendez-vous à venir","doctor.patient_search":"Recherche patient","doctor.clinical_tasks":"Tâches cliniques","doctor.notes":"Notes à compléter","doctor.results":"Résultats à revoir","doctor.followups":"Suivis",
"administration.dashboard":"Espace administration","administration.today":"Opérations du jour","administration.quick_actions":"Actions rapides","administration.new_appointment":"Nouveau rendez-vous","administration.manage_schedule":"Gérer le planning","administration.checkin":"Enregistrer l'arrivée",
"super.dashboard":"Super Admin / White Label","super.platform":"Plateforme","super.ai":"IA / Hani","super.navigation":"Navigation","super.access":"Accès","super.system":"Système","super.organizations":"Organisations & marque blanche","super.languages":"Langues","super.features":"Fonctionnalités","super.integrations":"Intégrations","super.logs":"Journaux d'audit","super.white_label":"Configuration White Label","super.branding":"Marque et organisation","super.ai_settings":"Configuration Hani / IA","super.map_settings":"Cartes et navigation","super.notification_settings":"Notifications","super.feature_settings":"Modules activés",
"accounts.title":"Gestion des comptes","accounts.subtitle":"Rôles par défaut avec surcharges individuelles optionnelles.","accounts.name":"Nom","accounts.email":"E-mail","accounts.role":"Rôle","accounts.department":"Service","accounts.status":"Statut","accounts.last_login":"Dernière connexion","accounts.created":"Créé le","accounts.active":"Actif","accounts.inactive":"Inactif","accounts.create":"Créer un compte","accounts.permissions":"Permissions assignées","accounts.deactivate":"Désactiver","accounts.activate":"Activer",
"staffapp.scheduling":"Planification","staffapp.appointments_title":"Rendez-vous","staffapp.appointments_lead":"État partagé avec les canaux patient et voix.","staffapp.people":"Personnes","staffapp.patients_title":"Patients","staffapp.patients_lead":"Identités synthétiques de compétition uniquement.","staffapp.provider_config":"Configuration prestataire","staffapp.services_title":"Services & horaires","staffapp.services_lead":"La configuration opérationnelle est stockée dans les données.","staffapp.weekly_rules":"Règles de disponibilité hebdomadaire","staffapp.analytics_title":"Analytique opérationnelle & IA","staffapp.analytics_lead":"Ces chiffres proviennent de l'état synthétique de démo.","staffapp.calls_title":"Appels, conversations et activité outils","staffapp.calls_lead":"Les actions de démonstration sont traçables.","staffapp.voice_lab":"Ouvrir le laboratoire vocal","staffapp.audit_title":"Journal d'audit","staffapp.audit_lead":"Traçabilité des accès et modifications sensibles.",
"status.confirmed":"Confirmé","status.cancelled":"Annulé","status.completed":"Terminé","status.requested":"Demandé","status.offered":"Proposé","status.no_show":"Absent","status.needs_assistance":"Assistance requise","status.active":"Actif","status.escalated":"Escaladé","status.failed":"Échec","status.success":"Succès","status.error":"Erreur","status.rejected":"Rejeté"
};
const en:Dictionary={...fr,
"common.save":"Save","common.cancel":"Cancel","common.confirm":"Confirm","common.view":"View","common.manage":"Manage","common.search":"Search","common.back":"Back","common.edit":"Edit","common.create":"Create","common.close":"Close","common.loading":"Loading…","common.active":"Active","common.inactive":"Inactive","common.yes":"Yes","common.no":"No","common.access_denied":"You do not have permission to access this section.","common.access_denied_hint":"Return to the Staff Console and open a workspace that matches your role.","common.synthetic":"Synthetic data","common.status":"Status","common.action":"Action","common.time":"Time","common.channel":"Channel","common.patient":"Patient","common.service":"Service",
"nav.home":"Home","nav.journey":"Journey","nav.map":"Map","nav.profile":"Profile","nav.overview":"Overview","nav.appointments":"Appointments","nav.patients":"Patients","nav.services":"Services","nav.calls":"Calls & Hani","nav.analytics":"Analytics","nav.settings":"Settings","nav.roles":"Roles & permissions","nav.accounts":"Accounts","nav.white_label":"White label","nav.audit":"Audit log","nav.notifications":"Notifications","nav.integrations":"Integrations",
"patient.navigation":"Patient navigation","patient.hello":"Hello","patient.with_you":"I'm with you.","patient.simple_lead":"One clear next step, without a complicated dashboard.","patient.next":"Your next step","patient.your_appointment":"Your appointment","patient.organize_visit":"Plan your visit","patient.organize_hint":"Find the service and choose an available time.","patient.book":"Book an appointment","patient.continue":"Continue journey","patient.guide":"Guide me","patient.talk":"Talk","patient.journey_glance":"Your journey at a glance","patient.progress":"Progress","patient.no_journey":"No active journey yet","patient.no_journey_hint":"A journey is created automatically after booking.","patient.phone_preference":"Prefer to call?","patient.phone_hint":"Same rules, same availability, voice interface.","patient.try":"Try it","patient.call":"Call Hani Maak","patient.help":"Need help","patient.prototype":"Prototype route — not validated by the hospital",
"services.eyebrow":"Access","services.title":"Which service do you need?","services.hint":"Choose a service to go directly to appointment selection.",
"booking.eyebrow":"Appointment","booking.title":"When would you like to come?","booking.lead":"Choose a date first, then select an available time.","booking.date":"Date","booking.preference":"Preference","booking.morning":"Morning","booking.afternoon":"Afternoon","booking.all_day":"All day","booking.show":"See available times","booking.searching":"Searching…","booking.available":"Available times","booking.none":"No available time for this date.","booking.place":"place","booking.places":"places","booking.summary":"Your appointment","booking.confirm":"Confirm this appointment","booking.confirming":"Confirming…","booking.selected":"Selected","booking.prep":"Bring to your appointment","booking.id":"Identity document","booking.rx":"Prescription or medical request if available","booking.note":"Any exam-specific instructions will be communicated or confirmed by the healthcare professional.","booking.search_error":"Unable to load available times. Please try again.","booking.confirm_error":"An error occurred while confirming. Please try again.",
"appointment.confirmed":"Appointment confirmed","appointment.reserved":"It's booked.","appointment.journey_created":"Your journey was created automatically with preparation, navigation, visit and follow-up.","appointment.view_journey":"View my journey","appointment.view_route":"View prototype route","appointment.move":"Reschedule appointment","appointment.new_slots":"New times","appointment.confirm_move":"Confirm reschedule","appointment.cancel":"Cancel appointment","appointment.cancel_confirm":"Cancel this appointment?","appointment.waitlist":"Notify me if an earlier time opens","appointment.waitlist_added":"You are on the alert list for an earlier time.",
"journey.eyebrow":"Continuity","journey.title":"Your journey","journey.lead":"A simple timeline: what is complete, what is next and what comes later.","journey.empty":"No active journey","journey.empty_hint":"Book an appointment to begin.","journey.understood":"I understand","journey.updating":"Updating…","journey.open_guidance":"Open guidance",
"profile.title":"Profile","profile.language":"Language","profile.channel":"Preferred channel","profile.data":"Data","profile.medicine":"Read a medicine package","profile.voice":"Test voice assistant","profile.caregiver":"Authorize a caregiver","profile.caregiver_hint":"Prototype delegation for appointments, journey and reminders.","profile.caregiver_name":"Caregiver name","profile.phone":"Phone","profile.authorize":"Authorize caregiver","profile.delegated":"Access delegated in the prototype.","profile.active_delegations":"active delegation(s) in the demo.","profile.production_note":"In production, permissions, consent and caregiver delegations will be managed here. The competition uses synthetic identities only.",
"map.eyebrow":"Guidance · Charles Nicolle","map.title":"I'll guide you to the service.","map.lead":"The route uses a deterministic graph. The indoor layer is explicitly a prototype.","map.prototype":"Prototype route — indoor campus not validated by the hospital.","map.real_context":"Real context","map.position":"My position","map.ar":"AR mode","map.step":"Step","map.remaining":"m remaining","map.start":"Start at the main entrance and follow the Hani Maak line.","map.continue":"Continue toward the destination.","map.accessible":"Accessible route","map.deterministic":"Deterministic guidance","map.arrived":"I reached this point","map.destination":"Destination reached.","map.unavailable":"Guidance unavailable.",
"medicine.eyebrow":"Continuity · Vision prototype","medicine.title":"Read my medicine package","medicine.lead":"Clarify visible package text and retrieve a recorded professional instruction.","medicine.safety":"This feature helps read package text and retrieve a recorded instruction. It does not decide whether you should take the medicine and never changes a dose.","medicine.choose":"Photograph or choose the package","medicine.read":"Read visible text","medicine.analyzing":"Analyzing…","medicine.detected":"Detected text — confirm it","medicine.name_unknown":"Name not detected","medicine.strength":"Strength","medicine.date":"Visible date","medicine.lot":"Lot","medicine.unknown":"unknown","medicine.not_detected":"not detected","medicine.instruction":"Recorded professional instruction — demo","medicine.expired":"The detected date has passed. Contact a pharmacist or healthcare professional; do not use this information alone to decide what to do.","medicine.not_expired":"The detected visible date has not passed. This does not establish that the medicine is appropriate or safe to use.",
"staff.title":"Staff Console","staff.subtitle":"Choose the workspace that matches your responsibility.","staff.role_overview":"Access levels","staff.what_can_access":"Information available","staff.what_can_manage":"Can manage","staff.open_workspace":"Open workspace","staff.view_permissions":"View permissions",
"roles.doctor":"Doctor","roles.doctor_summary":"Clinical care and the medical information required for treatment.","roles.administration":"Administration","roles.administration_summary":"Appointments, scheduling and patient operations without full clinical access.","roles.super_admin":"Super Admin / White Label","roles.super_admin_summary":"Platform, AI, accounts, languages, integrations and branding configuration.","roles.doctor_access":"General and clinical patient data, medical documents, appointments and notes.","roles.doctor_manage":"Clinical notes, instructions, appointment context and follow-up.","roles.administration_access":"General identity, contact details, appointments, services and schedules.","roles.administration_manage":"Appointments, schedules, services and daily operations.","roles.super_admin_access":"Technical configuration, accounts, roles, AI, maps, languages and analytics.","roles.super_admin_manage":"Global settings, permissions, white-label configuration, integrations and features.",
"permissions.title":"Permission matrix","permissions.patient_data":"Patient data","permissions.appointments":"Appointments","permissions.clinical":"Clinical","permissions.operations":"Operations","permissions.platform":"Platform","permissions.allowed":"Allowed","permissions.denied":"Restricted",
"doctor.dashboard":"Doctor workspace","doctor.today":"Today","doctor.upcoming":"Upcoming appointments","doctor.patient_search":"Patient search","doctor.clinical_tasks":"Clinical tasks","doctor.notes":"Notes to complete","doctor.results":"Results to review","doctor.followups":"Follow-ups",
"administration.dashboard":"Administration workspace","administration.today":"Today's operations","administration.quick_actions":"Quick actions","administration.new_appointment":"New appointment","administration.manage_schedule":"Manage schedule","administration.checkin":"Check in patient",
"super.dashboard":"Super Admin / White Label","super.platform":"Platform","super.ai":"AI / Hani","super.navigation":"Navigation","super.access":"Access","super.system":"System","super.organizations":"Organizations & white label","super.languages":"Languages","super.features":"Features","super.integrations":"Integrations","super.logs":"Audit logs","super.white_label":"White-label configuration","super.branding":"Brand & organization","super.ai_settings":"Hani / AI configuration","super.map_settings":"Maps & navigation","super.notification_settings":"Notifications","super.feature_settings":"Enabled modules",
"accounts.title":"Account management","accounts.subtitle":"Default roles with optional account-specific overrides.","accounts.name":"Name","accounts.email":"Email","accounts.role":"Role","accounts.department":"Department","accounts.status":"Status","accounts.last_login":"Last login","accounts.created":"Created","accounts.active":"Active","accounts.inactive":"Inactive","accounts.create":"Create account","accounts.permissions":"Assigned permissions","accounts.deactivate":"Deactivate","accounts.activate":"Activate",
"staffapp.scheduling":"Scheduling","staffapp.appointments_title":"Appointments","staffapp.appointments_lead":"State shared with patient and voice channels.","staffapp.people":"People","staffapp.patients_title":"Patients","staffapp.patients_lead":"Synthetic competition identities only.","staffapp.provider_config":"Provider configuration","staffapp.services_title":"Services & schedules","staffapp.services_lead":"Operational configuration is stored in data.","staffapp.weekly_rules":"Weekly availability rules","staffapp.analytics_title":"Operational & AI analytics","staffapp.analytics_lead":"These figures come from current synthetic demo state.","staffapp.calls_title":"Calls, conversations and tool activity","staffapp.calls_lead":"Demo actions are traceable.","staffapp.voice_lab":"Open voice lab","staffapp.audit_title":"Audit log","staffapp.audit_lead":"Trace sensitive access and changes.",
"status.confirmed":"Confirmed","status.cancelled":"Cancelled","status.completed":"Completed","status.requested":"Requested","status.offered":"Offered","status.no_show":"No show","status.needs_assistance":"Needs assistance","status.active":"Active","status.escalated":"Escalated","status.failed":"Failed","status.success":"Success","status.error":"Error","status.rejected":"Rejected"
};
const ar:Dictionary={...en,
"common.save":"حفظ","common.cancel":"إلغاء","common.confirm":"تأكيد","common.view":"عرض","common.manage":"إدارة","common.search":"بحث","common.back":"رجوع","common.edit":"تعديل","common.create":"إنشاء","common.close":"سكر","common.loading":"جاري التحميل…","common.active":"نشط","common.inactive":"غير نشط","common.access_denied":"ما عندكش صلاحية للدخول للقسم هذا.","common.access_denied_hint":"ارجع لفضاء الفريق وافتح المساحة المناسبة لدورك.","common.synthetic":"بيانات تجريبية","common.status":"الحالة","common.action":"إجراء","common.time":"الوقت","common.channel":"القناة","common.patient":"المريض","common.service":"الخدمة",
"nav.home":"الرئيسية","nav.journey":"مساري","nav.map":"الخريطة","nav.profile":"حسابي","nav.overview":"نظرة عامة","nav.appointments":"المواعيد","nav.patients":"المرضى","nav.services":"الخدمات","nav.calls":"المكالمات وهاني","nav.analytics":"الإحصائيات","nav.settings":"الإعدادات","nav.roles":"الأدوار والصلاحيات","nav.accounts":"الحسابات","nav.white_label":"الهوية الخاصة","nav.audit":"سجل التدقيق","nav.notifications":"الإشعارات","nav.integrations":"التكاملات",
"patient.navigation":"تنقل المريض","patient.hello":"عسلامة","patient.with_you":"هاني معاك.","patient.simple_lead":"كل مرة خطوة واضحة، من غير تعقيد.","patient.next":"خطوتك القادمة","patient.your_appointment":"موعدك","patient.organize_visit":"نظّم زيارتك","patient.organize_hint":"اختار المصلحة والوقت المتاح.","patient.book":"احجز موعداً","patient.continue":"واصل المسار","patient.guide":"دلّني","patient.talk":"احكي","patient.journey_glance":"مسارك في لمحة","patient.progress":"التقدم","patient.no_journey":"ما عندكش مسار نشط توّا","patient.no_journey_hint":"المسار يتعمل آلياً بعد تأكيد الموعد.","patient.phone_preference":"تحب تتصل بالتليفون؟","patient.phone_hint":"نفس القواعد ونفس المواعيد بمساعد صوتي.","patient.try":"جرّب","patient.call":"اتصل بهاني معاك","patient.help":"تحتاج مساعدة؟","patient.prototype":"مسار تجريبي — غير معتمد من المستشفى",
"services.eyebrow":"الوصول","services.title":"شنوة المصلحة اللي تحتاجها؟","services.hint":"اختار المصلحة وامشي مباشرة لاختيار الموعد.",
"booking.eyebrow":"موعد","booking.title":"وقتاش تحب تجي؟","booking.lead":"اختار التاريخ أولاً، وبعدها اختار الوقت المتاح.","booking.date":"التاريخ","booking.preference":"الفترة","booking.morning":"الصباح","booking.afternoon":"بعد الظهر","booking.all_day":"النهار الكل","booking.show":"شوف المواعيد المتاحة","booking.searching":"جاري البحث…","booking.available":"الأوقات المتاحة","booking.none":"ما فماش موعد متاح في التاريخ هذا.","booking.place":"بلاصة","booking.places":"بلايص","booking.summary":"موعدك","booking.confirm":"أكد الموعد","booking.confirming":"جاري التأكيد…","booking.selected":"تم الاختيار","booking.prep":"شنوة يلزمك للموعد","booking.id":"بطاقة تعريف","booking.rx":"وصفة أو طلب طبي إذا متوفر","booking.note":"أي تعليمات خاصة بالفحص يثبتها أو يبعثها المهني الصحي.","booking.search_error":"تعذر تحميل المواعيد. عاود حاول.","booking.confirm_error":"صار مشكل وقت تأكيد الموعد. عاود حاول.",
"appointment.confirmed":"الموعد مؤكد","appointment.reserved":"الموعد تحجز.","appointment.journey_created":"المسار تعمل آلياً: التحضير، الطريق، الزيارة والمتابعة.","appointment.view_journey":"شوف مساري","appointment.view_route":"شوف المسار التجريبي","appointment.move":"بدّل الموعد","appointment.new_slots":"مواعيد جديدة","appointment.confirm_move":"أكد التغيير","appointment.cancel":"ألغي الموعد","appointment.cancel_confirm":"متأكد تحب تلغي الموعد؟","appointment.waitlist":"علّمني كان يخرج موعد أقرب","appointment.waitlist_added":"ضفناك لقائمة التنبيه لموعد أقرب.",
"journey.eyebrow":"المتابعة","journey.title":"مسارك","journey.lead":"مسار بسيط: شنو كمل، شنو توّا، وشنو بعد.","journey.empty":"ما فماش مسار نشط","journey.empty_hint":"احجز موعد باش يبدأ المسار.","journey.understood":"فهمت","journey.updating":"جاري التحديث…","journey.open_guidance":"افتح التوجيه",
"profile.title":"حسابي","profile.language":"اللغة","profile.channel":"القناة المفضلة","profile.data":"البيانات","profile.medicine":"اقرا علبة الدواء","profile.voice":"جرّب المساعد الصوتي","profile.caregiver":"فوّض قريب","profile.caregiver_hint":"تفويض تجريبي للمواعيد والمسار والتذكير.","profile.caregiver_name":"اسم القريب","profile.phone":"التليفون","profile.authorize":"فوّض القريب","profile.delegated":"تم التفويض في النسخة التجريبية.","profile.active_delegations":"تفويض نشط في الديمو.","profile.production_note":"في الإنتاج، الصلاحيات والموافقات وتفويض القريب يتداروا هنا. المسابقة تستعمل هويات اصطناعية فقط.",
"map.eyebrow":"التوجيه · شارل نيكول","map.title":"نوصلك للمصلحة.","map.lead":"المسار يتحسب بقواعد ثابتة. المسار الداخلي تجريبي وغير معتمد من المستشفى.","map.prototype":"مسار تجريبي — داخل المستشفى غير معتمد.","map.real_context":"الموقع الحقيقي","map.position":"موقعي","map.ar":"وضع AR","map.step":"المرحلة","map.remaining":"متر باقي","map.start":"ابدأ من المدخل الرئيسي واتبع خط هاني معاك.","map.continue":"واصل للوجهة.","map.accessible":"مسار مهيأ","map.deterministic":"توجيه ثابت","map.arrived":"وصلت للنقطة هاذي","map.destination":"وصلت للوجهة.","map.unavailable":"التوجيه موش متاح.",
"medicine.eyebrow":"المتابعة · نموذج الرؤية","medicine.title":"اقرا علبة الدواء","medicine.lead":"نوضح النص الظاهر على العلبة ونجيب تعليمات مهنية مسجلة.","medicine.safety":"الميزة تساعد فقط في قراءة النص واسترجاع تعليمات مسجلة. ما تقررش إذا لازم تاخذ الدواء وما تبدلش الجرعة.","medicine.choose":"صوّر أو اختار العلبة","medicine.read":"اقرا النص الظاهر","medicine.analyzing":"جاري التحليل…","medicine.detected":"النص المكتشف — يلزم التأكيد","medicine.name_unknown":"الاسم موش واضح","medicine.strength":"التركيز","medicine.date":"التاريخ الظاهر","medicine.lot":"الدفعة","medicine.unknown":"غير معروف","medicine.not_detected":"موش واضح","medicine.instruction":"تعليمات مهنية مسجلة — ديمو","medicine.expired":"التاريخ المكتشف فات. اتصل بصيدلي أو مهني صحي وما تعتمدش على المعلومة وحدها.","medicine.not_expired":"التاريخ الظاهر ما فاتش، أما هذا ما يثبتش أن الدواء مناسب أو آمن للاستعمال.",
"staff.title":"فضاء الفريق","staff.subtitle":"اختار الفضاء المناسب حسب مسؤوليتك.","staff.role_overview":"مستويات النفاذ","staff.what_can_access":"المعلومات المتاحة","staff.what_can_manage":"ما يمكن إدارته","staff.open_workspace":"افتح الفضاء","staff.view_permissions":"شوف الصلاحيات",
"roles.doctor":"طبيب","roles.doctor_summary":"رعاية سريرية ونفاذ للمعلومات الطبية اللازمة للعلاج.","roles.administration":"الإدارة","roles.administration_summary":"المواعيد والجدولة وعمليات المرضى دون نفاذ كامل للبيانات السريرية.","roles.super_admin":"المشرف العام / White Label","roles.super_admin_summary":"إعداد المنصة والذكاء الاصطناعي والحسابات واللغات والتكاملات والهوية.","roles.doctor_access":"بيانات عامة وسريرية للمريض، وثائق طبية، مواعيد وملاحظات.","roles.doctor_manage":"ملاحظات سريرية، تعليمات، سياق الموعد والمتابعة الطبية.","roles.administration_access":"الهوية العامة، الاتصال، المواعيد، الخدمات والجدولة.","roles.administration_manage":"المواعيد، الجداول، الخدمات والعمليات اليومية.","roles.super_admin_access":"الإعداد التقني، الحسابات، الأدوار، الذكاء الاصطناعي، الخرائط، اللغات والإحصائيات.","roles.super_admin_manage":"الإعدادات العامة، الصلاحيات، الهوية الخاصة، التكاملات والميزات.",
"permissions.title":"مصفوفة الصلاحيات","permissions.patient_data":"بيانات المريض","permissions.appointments":"المواعيد","permissions.clinical":"السريري","permissions.operations":"العمليات","permissions.platform":"المنصة","permissions.allowed":"مسموح","permissions.denied":"مقيّد",
"doctor.dashboard":"فضاء الطبيب","doctor.today":"اليوم","doctor.upcoming":"المواعيد القادمة","doctor.patient_search":"بحث عن مريض","doctor.clinical_tasks":"مهام سريرية","doctor.notes":"ملاحظات ناقصة","doctor.results":"نتائج للمراجعة","doctor.followups":"متابعة",
"administration.dashboard":"فضاء الإدارة","administration.today":"عمليات اليوم","administration.quick_actions":"إجراءات سريعة","administration.new_appointment":"موعد جديد","administration.manage_schedule":"إدارة الجدول","administration.checkin":"تسجيل وصول المريض",
"super.dashboard":"المشرف العام / White Label","super.platform":"المنصة","super.ai":"الذكاء الاصطناعي / هاني","super.navigation":"الملاحة","super.access":"النفاذ","super.system":"النظام","super.organizations":"المؤسسات والهوية","super.languages":"اللغات","super.features":"الميزات","super.integrations":"التكاملات","super.logs":"سجل التدقيق","super.white_label":"إعداد الهوية الخاصة","super.branding":"الهوية والمؤسسة","super.ai_settings":"إعداد هاني والذكاء الاصطناعي","super.map_settings":"الخرائط والتوجيه","super.notification_settings":"الإشعارات","super.feature_settings":"الوحدات المفعلة",
"accounts.title":"إدارة الحسابات","accounts.subtitle":"أدوار افتراضية مع إمكانية تعديل صلاحيات حساب بعينه.","accounts.name":"الاسم","accounts.email":"البريد الإلكتروني","accounts.role":"الدور","accounts.department":"القسم","accounts.status":"الحالة","accounts.last_login":"آخر دخول","accounts.created":"تاريخ الإنشاء","accounts.active":"نشط","accounts.inactive":"غير نشط","accounts.create":"إنشاء حساب","accounts.permissions":"الصلاحيات","accounts.deactivate":"تعطيل","accounts.activate":"تفعيل",
"staffapp.scheduling":"الجدولة","staffapp.appointments_title":"المواعيد","staffapp.appointments_lead":"نفس الحالة مشتركة مع تطبيق المريض والصوت.","staffapp.people":"المرضى","staffapp.patients_title":"المرضى","staffapp.patients_lead":"هويات اصطناعية للمسابقة فقط.","staffapp.provider_config":"إعداد المرفق","staffapp.services_title":"الخدمات والجداول","staffapp.services_lead":"الإعدادات التشغيلية مخزنة في البيانات.","staffapp.weekly_rules":"قواعد التوفر الأسبوعية","staffapp.analytics_title":"إحصائيات التشغيل والذكاء الاصطناعي","staffapp.analytics_lead":"الأرقام من حالة الديمو الاصطناعية الحالية.","staffapp.calls_title":"المكالمات والمحادثات وأدوات هاني","staffapp.calls_lead":"كل إجراء في الديمو قابل للتتبع.","staffapp.voice_lab":"افتح مختبر الصوت","staffapp.audit_title":"سجل التدقيق","staffapp.audit_lead":"تتبع النفاذ والتعديلات الحساسة.",
"status.confirmed":"مؤكد","status.cancelled":"ملغى","status.completed":"مكتمل","status.requested":"مطلوب","status.offered":"مقترح","status.no_show":"لم يحضر","status.needs_assistance":"يحتاج مساعدة","status.active":"نشط","status.escalated":"محال لموظف","status.failed":"فشل","status.success":"نجاح","status.error":"خطأ","status.rejected":"مرفوض"
};
export const dictionaries:Record<Locale,Dictionary>={fr,en,ar};
export function t(locale:Locale,key:string,fallback?:string){return dictionaries[locale][key]??fr[key]??fallback??key}
export function statusText(locale:Locale,value:string){return t(locale,`status.${value}`,value)}
export const text={fr:{home:t("fr","nav.home"),journey:t("fr","nav.journey"),map:t("fr","nav.map"),profile:t("fr","nav.profile"),next:t("fr","patient.next"),book:t("fr","patient.book"),guide:t("fr","patient.guide"),call:t("fr","patient.call"),help:t("fr","patient.help"),prototype:t("fr","patient.prototype")},ar:{home:t("ar","nav.home"),journey:t("ar","nav.journey"),map:t("ar","nav.map"),profile:t("ar","nav.profile"),next:t("ar","patient.next"),book:t("ar","patient.book"),guide:t("ar","patient.guide"),call:t("ar","patient.call"),help:t("ar","patient.help"),prototype:t("ar","patient.prototype")},en:{home:t("en","nav.home"),journey:t("en","nav.journey"),map:t("en","nav.map"),profile:t("en","nav.profile"),next:t("en","patient.next"),book:t("en","patient.book"),guide:t("en","patient.guide"),call:t("en","patient.call"),help:t("en","patient.help"),prototype:t("en","patient.prototype")}};
