import type {Locale} from "./types";import {t} from "./i18n";
type D=Record<string,string>;const fr:D={
"staff.complete":"Marquer la visite terminée","staff.updating":"Mise à jour…","staff.recent":"Récent","staff.open":"Ouvrir","staff.general_only":"Informations administratives générales uniquement.","staff.medical_private":"Les données cliniques sont réservées aux médecins autorisés.","staff.no_data":"Aucune donnée disponible.","staff.configuration":"Configuration","staff.schedule":"Planning","staff.exceptions":"Exceptions","staff.demo_metrics":"Mesures de démonstration","staff.events":"Événements récents","staff.ai_targets":"Objectifs d'évaluation IA","staff.calls_empty":"Aucune session d'appel pour le moment.",
"clinical.title":"Dossier clinique","clinical.identity":"Identité et contact","clinical.appointments":"Contexte des rendez-vous","clinical.documents":"Documents médicaux","clinical.notes":"Notes cliniques","clinical.add_note":"Ajouter une note clinique","clinical.note_placeholder":"Note clinique de démonstration…","clinical.no_notes":"Aucune note clinique enregistrée.","clinical.no_documents":"Aucun document médical enregistré.","clinical.history":"Historique médical","clinical.history_empty":"Aucun historique médical structuré n'est disponible dans les données de démonstration.","clinical.save_note":"Enregistrer la note",
"settings.title":"Paramètres système","settings.lead":"Configuration technique et opérationnelle du tenant.","content.title":"Contenus & instructions","content.lead":"Instructions publiées utilisées dans les parcours patient.","mapadmin.title":"Carte & navigation","mapadmin.lead":"Waypoints du prototype intérieur. Ces données ne sont pas validées par l'hôpital.","journeys.title":"Parcours & suivi","journeys.lead":"Suivi administratif des parcours patients.","calls.title":"Appels, conversations & outils Hani","calls.lead":"Trace auditable des sessions vocales et actions outils.","analytics.evidence":"Preuves, sans impact inventé",
"editor.provider_name":"Nom affiché de l'établissement","editor.primary":"Couleur principale","editor.accent":"Couleur secondaire","editor.save_brand":"Enregistrer la marque","editor.name_fr":"Nom français","editor.name_ar":"Nom arabe","editor.name_en":"Nom anglais","editor.slot_duration":"Durée du créneau (min)","editor.save_service":"Enregistrer le service","editor.published":"Publié","editor.save_content":"Enregistrer le contenu","editor.label_fr":"Libellé français","editor.label_ar":"Libellé arabe","editor.label_en":"Libellé anglais","editor.start":"Début","editor.end":"Fin","editor.capacity":"Capacité","editor.day":"Jour","editor.save_rule":"Enregistrer la règle","editor.saving":"Enregistrement…",
"days.0":"Dim","days.1":"Lun","days.2":"Mar","days.3":"Mer","days.4":"Jeu","days.5":"Ven","days.6":"Sam","analytics.appointments_today":"Rendez-vous aujourd'hui","analytics.completed":"Visites terminées","analytics.open_escalations":"Escalades ouvertes","analytics.voice_sessions":"Sessions vocales","analytics.tool_success":"Actions outils réussies","analytics.journey_completion":"Parcours terminés","calls.session":"Session","calls.transcript":"Transcription","calls.tools":"Outils","calls.escalation":"Escalade","settings.brand":"Identité visuelle","settings.security":"Sécurité et accès","settings.storage":"Persistance","settings.demo":"Mode démonstration"};
const en:D={...fr,
"staff.complete":"Mark visit complete","staff.updating":"Updating…","staff.recent":"Recent","staff.open":"Open","staff.general_only":"General administrative information only.","staff.medical_private":"Clinical data is restricted to authorized doctors.","staff.no_data":"No data available.","staff.configuration":"Configuration","staff.schedule":"Schedule","staff.exceptions":"Exceptions","staff.demo_metrics":"Demo metrics","staff.events":"Recent events","staff.ai_targets":"AI evaluation targets","staff.calls_empty":"No call sessions yet.",
"clinical.title":"Clinical record","clinical.identity":"Identity & contact","clinical.appointments":"Appointment context","clinical.documents":"Medical documents","clinical.notes":"Clinical notes","clinical.add_note":"Add clinical note","clinical.note_placeholder":"Demo clinical note…","clinical.no_notes":"No clinical notes recorded.","clinical.no_documents":"No medical documents recorded.","clinical.history":"Medical history","clinical.history_empty":"No structured medical history is available in the demonstration data.","clinical.save_note":"Save note",
"settings.title":"System settings","settings.lead":"Technical and operational tenant configuration.","content.title":"Content & instructions","content.lead":"Published instructions used in patient journeys.","mapadmin.title":"Map & navigation","mapadmin.lead":"Prototype indoor waypoints. These data are not validated by the hospital.","journeys.title":"Journeys & follow-up","journeys.lead":"Administrative follow-up of patient journeys.","calls.title":"Calls, conversations & Hani tools","calls.lead":"Auditable trace of voice sessions and tool actions.","analytics.evidence":"Evidence, not invented impact",
"editor.provider_name":"Provider display name","editor.primary":"Primary color","editor.accent":"Accent color","editor.save_brand":"Save branding","editor.name_fr":"French name","editor.name_ar":"Arabic name","editor.name_en":"English name","editor.slot_duration":"Slot duration (min)","editor.save_service":"Save service","editor.published":"Published","editor.save_content":"Save content","editor.label_fr":"French label","editor.label_ar":"Arabic label","editor.label_en":"English label","editor.start":"Start","editor.end":"End","editor.capacity":"Capacity","editor.day":"Day","editor.save_rule":"Save rule","editor.saving":"Saving…",
"days.0":"Sun","days.1":"Mon","days.2":"Tue","days.3":"Wed","days.4":"Thu","days.5":"Fri","days.6":"Sat","analytics.appointments_today":"Appointments today","analytics.completed":"Completed visits","analytics.open_escalations":"Open escalations","analytics.voice_sessions":"Voice sessions","analytics.tool_success":"Successful tool actions","analytics.journey_completion":"Completed journeys","calls.session":"Session","calls.transcript":"Transcript","calls.tools":"Tools","calls.escalation":"Escalation","settings.brand":"Branding","settings.security":"Security & access","settings.storage":"Persistence","settings.demo":"Demo mode"};
const ar:D={...en,
"staff.complete":"سجّل الزيارة كمكتملة","staff.updating":"جاري التحديث…","staff.recent":"الأحدث","staff.open":"افتح","staff.general_only":"معلومات إدارية عامة فقط.","staff.medical_private":"البيانات السريرية متاحة فقط للأطباء المرخص لهم.","staff.no_data":"ما فماش بيانات.","staff.configuration":"الإعداد","staff.schedule":"الجدول","staff.exceptions":"الاستثناءات","staff.demo_metrics":"مؤشرات الديمو","staff.events":"آخر الأحداث","staff.ai_targets":"أهداف تقييم الذكاء الاصطناعي","staff.calls_empty":"ما فماش مكالمات توّا.",
"clinical.title":"الملف السريري","clinical.identity":"الهوية والاتصال","clinical.appointments":"سياق المواعيد","clinical.documents":"الوثائق الطبية","clinical.notes":"الملاحظات السريرية","clinical.add_note":"أضف ملاحظة سريرية","clinical.note_placeholder":"ملاحظة سريرية تجريبية…","clinical.no_notes":"ما فماش ملاحظات سريرية مسجلة.","clinical.no_documents":"ما فماش وثائق طبية مسجلة.","clinical.history":"التاريخ الطبي","clinical.history_empty":"ما فماش تاريخ طبي منظم في بيانات الديمو.","clinical.save_note":"احفظ الملاحظة",
"settings.title":"إعدادات النظام","settings.lead":"الإعداد التقني والتشغيلي للمؤسسة.","content.title":"المحتوى والتعليمات","content.lead":"تعليمات منشورة تستعمل في مسار المريض.","mapadmin.title":"الخريطة والتوجيه","mapadmin.lead":"نقاط داخلية تجريبية وغير معتمدة من المستشفى.","journeys.title":"المسارات والمتابعة","journeys.lead":"متابعة إدارية لمسارات المرضى.","calls.title":"المكالمات والمحادثات وأدوات هاني","calls.lead":"سجل قابل للتدقيق للمكالمات وإجراءات الأدوات.","analytics.evidence":"أدلة من الديمو بدون ادعاءات غير مقاسة",
"editor.provider_name":"اسم المؤسسة","editor.primary":"اللون الرئيسي","editor.accent":"اللون الثانوي","editor.save_brand":"احفظ الهوية","editor.name_fr":"الاسم بالفرنسية","editor.name_ar":"الاسم بالعربية","editor.name_en":"الاسم بالإنجليزية","editor.slot_duration":"مدة الموعد بالدقائق","editor.save_service":"احفظ الخدمة","editor.published":"منشور","editor.save_content":"احفظ المحتوى","editor.label_fr":"الاسم بالفرنسية","editor.label_ar":"الاسم بالعربية","editor.label_en":"الاسم بالإنجليزية","editor.start":"البداية","editor.end":"النهاية","editor.capacity":"السعة","editor.day":"اليوم","editor.save_rule":"احفظ القاعدة","editor.saving":"جاري الحفظ…",
"days.0":"أحد","days.1":"اثنين","days.2":"ثلاثاء","days.3":"أربعاء","days.4":"خميس","days.5":"جمعة","days.6":"سبت","analytics.appointments_today":"مواعيد اليوم","analytics.completed":"زيارات مكتملة","analytics.open_escalations":"تصعيدات مفتوحة","analytics.voice_sessions":"جلسات صوتية","analytics.tool_success":"إجراءات أدوات ناجحة","analytics.journey_completion":"مسارات مكتملة","calls.session":"جلسة","calls.transcript":"النص","calls.tools":"الأدوات","calls.escalation":"التصعيد","settings.brand":"الهوية","settings.security":"الأمان والنفاذ","settings.storage":"التخزين","settings.demo":"وضع الديمو"};
const all:Record<Locale,D>={fr,en,ar};export function stx(locale:Locale,key:string,fallback?:string){return all[locale][key]??all.fr[key]??t(locale,key,fallback)}
